<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGMDJsJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGMDJsJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGMDJsJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGMDJsJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGMDJsJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGMDJsJ',
    'container.build_id' => '707c5a90',
    'container.build_time' => 1638179626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGMDJsJ');
