<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5eMHKR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5eMHKR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5eMHKR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ5eMHKR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ5eMHKR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q5eMHKR',
    'container.build_id' => '171db03d',
    'container.build_time' => 1638102358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5eMHKR');
