<?php

namespace ContainerPGMDJsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZVe1AT7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZVe1AT7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZVe1AT7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ScoresController::Newscore' => ['privates', '.service_locator.2YhVWT9', 'get_ServiceLocator_2YhVWT9Service', true],
            'App\\Controller\\ScoresController::index' => ['privates', '.service_locator._N6NF7w', 'get_ServiceLocator_N6NF7wService', true],
            'App\\Controller\\ScoresController::total' => ['privates', '.service_locator._N6NF7w', 'get_ServiceLocator_N6NF7wService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ScoresController:Newscore' => ['privates', '.service_locator.2YhVWT9', 'get_ServiceLocator_2YhVWT9Service', true],
            'App\\Controller\\ScoresController:index' => ['privates', '.service_locator._N6NF7w', 'get_ServiceLocator_N6NF7wService', true],
            'App\\Controller\\ScoresController:total' => ['privates', '.service_locator._N6NF7w', 'get_ServiceLocator_N6NF7wService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ScoresController::Newscore' => '?',
            'App\\Controller\\ScoresController::index' => '?',
            'App\\Controller\\ScoresController::total' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ScoresController:Newscore' => '?',
            'App\\Controller\\ScoresController:index' => '?',
            'App\\Controller\\ScoresController:total' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
